import type {
  DashboardSnapshot,
  FluxoOperacional,
  Pedido,
  Produto,
  Revista,
  Vendedora,
} from "./types";

export const mockVendedoras: Vendedora[] = [
  {
    id: "ven-ana",
    nome: "Ana Souza",
    email: "ana@revistas.app",
    whatsapp: "5511998544332",
    telefone: "5511998544332",
    percentualComissao: 30,
    cidade: "Osasco",
    ativa: true,
    totalMes: 1840.9,
    pedidosPendentes: 1,
    ultimaVendaEm: "2026-05-03T14:30:00.000Z",
    revistasAtivas: ["Avon Ciclo 10", "Natura Ciclo 8"],
    observacoes:
      "Tem giro forte em maquiagem e costuma fechar o pedido no começo da semana.",
  },
  {
    id: "ven-carla",
    nome: "Carla Mendes",
    email: "carla@revistas.app",
    whatsapp: "5511987721122",
    telefone: "5511987721122",
    percentualComissao: 25,
    cidade: "Guarulhos",
    ativa: true,
    totalMes: 1320.4,
    pedidosPendentes: 2,
    ultimaVendaEm: "2026-05-02T17:10:00.000Z",
    revistasAtivas: ["Avon Ciclo 10"],
    observacoes:
      "Prefere comissão fixa e manda pedidos quase sempre por áudio no WhatsApp.",
  },
  {
    id: "ven-julia",
    nome: "Juliana Costa",
    email: "juliana@revistas.app",
    whatsapp: "5511976543210",
    telefone: "5511976543210",
    percentualComissao: 20,
    cidade: "Campinas",
    ativa: true,
    totalMes: 980.5,
    pedidosPendentes: 0,
    ultimaVendaEm: "2026-04-29T11:00:00.000Z",
    revistasAtivas: ["Eudora Maio"],
    observacoes: "Tem bom volume em kits promocionais.",
  },
  {
    id: "ven-renata",
    nome: "Renata Alves",
    email: "renata@revistas.app",
    whatsapp: "5511944412233",
    telefone: "5511944412233",
    percentualComissao: 30,
    cidade: "São Paulo",
    ativa: true,
    totalMes: 2105.3,
    pedidosPendentes: 1,
    ultimaVendaEm: "2026-05-01T19:20:00.000Z",
    revistasAtivas: ["Natura Ciclo 8", "Eudora Maio"],
    observacoes: "Consegue vender bem acessórios com margem diferenciada.",
  },
  {
    id: "ven-pri",
    nome: "Priscila Lima",
    email: "priscila@revistas.app",
    whatsapp: "5511933345566",
    telefone: "5511933345566",
    percentualComissao: 22,
    cidade: "Barueri",
    ativa: false,
    totalMes: 0,
    pedidosPendentes: 0,
    ultimaVendaEm: "2026-04-17T15:40:00.000Z",
    revistasAtivas: [],
    observacoes:
      "Cadastro pausado enquanto reorganiza a carteira de clientes.",
  },
];

export const mockRevistas: Revista[] = [
  {
    id: "rev-avon-10",
    titulo: "Avon",
    edicao: "Ciclo 10",
    vigenciaInicio: "2026-05-01",
    vigenciaFim: "2026-05-20",
    ativa: true,
    margemPadrao: 30,
    catalogoUrl: "https://example.com/catalogos/avon-ciclo-10.pdf",
    catalogoNomeArquivo: "avon-ciclo-10.pdf",
    textoCompartilhamento:
      "Catalogo Avon Ciclo 10 pronto para compartilhar com as clientes.",
  },
  {
    id: "rev-natura-8",
    titulo: "Natura",
    edicao: "Ciclo 8",
    vigenciaInicio: "2026-04-28",
    vigenciaFim: "2026-05-18",
    ativa: true,
    margemPadrao: 25,
    catalogoUrl: "https://example.com/catalogos/natura-ciclo-8.pdf",
    catalogoNomeArquivo: "natura-ciclo-8.pdf",
    textoCompartilhamento:
      "Catalogo Natura Ciclo 8 com os produtos da campanha atual.",
  },
  {
    id: "rev-eudora-maio",
    titulo: "Eudora",
    edicao: "Maio",
    vigenciaInicio: "2026-05-01",
    vigenciaFim: "2026-05-31",
    ativa: true,
    margemPadrao: 28,
    catalogoUrl: "https://example.com/catalogos/eudora-maio.pdf",
    catalogoNomeArquivo: "eudora-maio.pdf",
    textoCompartilhamento:
      "Catalogo Eudora de maio pronto para envio no WhatsApp.",
  },
];

export const mockProdutos: Produto[] = [
  {
    id: "pro-av-001",
    revistaId: "rev-avon-10",
    revistaTitulo: "Avon Ciclo 10",
    codigo: "AV-001",
    nome: "Batom Matte Rosa",
    categoria: "Maquiagem",
    precoCatalogo: 29.9,
    estoqueAtual: 18,
    margemComissao: 30,
  },
  {
    id: "pro-av-007",
    revistaId: "rev-avon-10",
    revistaTitulo: "Avon Ciclo 10",
    codigo: "AV-007",
    nome: "Máscara de Cílios Power",
    categoria: "Maquiagem",
    precoCatalogo: 42.5,
    estoqueAtual: 12,
    margemComissao: 30,
  },
  {
    id: "pro-nat-013",
    revistaId: "rev-natura-8",
    revistaTitulo: "Natura Ciclo 8",
    codigo: "NT-013",
    nome: "Hidratante Tododia Algodão",
    categoria: "Cuidados pessoais",
    precoCatalogo: 48.9,
    estoqueAtual: 20,
    margemComissao: 25,
  },
  {
    id: "pro-nat-025",
    revistaId: "rev-natura-8",
    revistaTitulo: "Natura Ciclo 8",
    codigo: "NT-025",
    nome: "Sabonete Líquido Ekos",
    categoria: "Banho",
    precoCatalogo: 34.9,
    estoqueAtual: 16,
    margemComissao: 25,
  },
  {
    id: "pro-eu-014",
    revistaId: "rev-eudora-maio",
    revistaTitulo: "Eudora Maio",
    codigo: "ED-014",
    nome: "Kit Siage Reconstrói",
    categoria: "Cabelos",
    precoCatalogo: 89.9,
    estoqueAtual: 9,
    margemComissao: 28,
  },
  {
    id: "pro-eu-022",
    revistaId: "rev-eudora-maio",
    revistaTitulo: "Eudora Maio",
    codigo: "ED-022",
    nome: "Bolsa Mini Glam",
    categoria: "Acessórios",
    precoCatalogo: 119.9,
    estoqueAtual: 5,
    margemComissao: 32,
  },
];

export const mockPedidos: Pedido[] = [
  {
    id: "ped-501",
    codigo: "PED-240501",
    vendedoraId: "ven-ana",
    vendedoraNome: "Ana Souza",
    status: "pendente",
    criadoEm: "2026-05-03T14:45:00.000Z",
    valorTotal: 189.8,
    comissaoCalculada: 56.94,
    itens: [
      {
        id: "ped-501-1",
        produtoId: "pro-av-001",
        produtoNome: "Batom Matte Rosa",
        revistaTitulo: "Avon Ciclo 10",
        quantidade: 2,
        precoUnitario: 29.9,
        percentualComissao: 30,
      },
      {
        id: "ped-501-2",
        produtoId: "pro-nat-013",
        produtoNome: "Hidratante Tododia Algodão",
        revistaTitulo: "Natura Ciclo 8",
        quantidade: 1,
        precoUnitario: 48.9,
        percentualComissao: 25,
      },
      {
        id: "ped-501-3",
        produtoId: "pro-eu-014",
        produtoNome: "Kit Siage Reconstrói",
        revistaTitulo: "Eudora Maio",
        quantidade: 1,
        precoUnitario: 89.9,
        percentualComissao: 28,
      },
    ],
  },
  {
    id: "ped-502",
    codigo: "PED-240502",
    vendedoraId: "ven-carla",
    vendedoraNome: "Carla Mendes",
    status: "separacao",
    criadoEm: "2026-05-02T17:25:00.000Z",
    valorTotal: 154.4,
    comissaoCalculada: 38.6,
    itens: [
      {
        id: "ped-502-1",
        produtoId: "pro-av-007",
        produtoNome: "Máscara de Cílios Power",
        revistaTitulo: "Avon Ciclo 10",
        quantidade: 2,
        precoUnitario: 42.5,
        percentualComissao: 30,
      },
      {
        id: "ped-502-2",
        produtoId: "pro-nat-025",
        produtoNome: "Sabonete Líquido Ekos",
        revistaTitulo: "Natura Ciclo 8",
        quantidade: 2,
        precoUnitario: 34.7,
        percentualComissao: 25,
      },
    ],
  },
  {
    id: "ped-503",
    codigo: "PED-240503",
    vendedoraId: "ven-renata",
    vendedoraNome: "Renata Alves",
    status: "pago",
    criadoEm: "2026-05-01T19:35:00.000Z",
    valorTotal: 239.8,
    comissaoCalculada: 71.94,
    itens: [
      {
        id: "ped-503-1",
        produtoId: "pro-eu-022",
        produtoNome: "Bolsa Mini Glam",
        revistaTitulo: "Eudora Maio",
        quantidade: 1,
        precoUnitario: 119.9,
        percentualComissao: 32,
      },
      {
        id: "ped-503-2",
        produtoId: "pro-eu-014",
        produtoNome: "Kit Siage Reconstrói",
        revistaTitulo: "Eudora Maio",
        quantidade: 1,
        precoUnitario: 89.9,
        percentualComissao: 28,
      },
      {
        id: "ped-503-3",
        produtoId: "pro-av-001",
        produtoNome: "Batom Matte Rosa",
        revistaTitulo: "Avon Ciclo 10",
        quantidade: 1,
        precoUnitario: 30,
        percentualComissao: 30,
      },
    ],
  },
];

const fluxo: FluxoOperacional[] = [
  {
    destaque: "Passo 1",
    titulo: "Cadastro da vendedora",
    descricao:
      "Defina comissão padrão, telefone e se a vendedora está ativa antes de começar a registrar pedidos.",
  },
  {
    destaque: "Passo 2",
    titulo: "Catálogo da revista",
    descricao:
      "Cada edição da revista organiza os produtos, seus códigos e preços para reduzir erro de lançamento.",
  },
  {
    destaque: "Passo 3",
    titulo: "Mensagem pronta no WhatsApp",
    descricao:
      "O pedido pode nascer como link wa.me com os itens já montados para acelerar o atendimento.",
  },
  {
    destaque: "Passo 4",
    titulo: "Fechamento e comissão",
    descricao:
      "Depois da confirmação, o painel acompanha status, valor total e quanto pagar para cada vendedora.",
  },
];

const faturamentoMes = mockPedidos.reduce(
  (sum, pedido) => sum + pedido.valorTotal,
  0,
);

const resumo = {
  totalVendedoras: mockVendedoras.length,
  revistasAtivas: mockRevistas.filter((item) => item.ativa).length,
  pedidosPendentes: mockPedidos.filter(
    (pedido) => pedido.status === "pendente" || pedido.status === "separacao",
  ).length,
  comissoesPrevistas: mockPedidos.reduce(
    (sum, pedido) => sum + pedido.comissaoCalculada,
    0,
  ),
  ticketMedio: faturamentoMes / mockPedidos.length,
  faturamentoMes,
};

export const mockDashboardSnapshot: DashboardSnapshot = {
  resumo,
  vendedoras: mockVendedoras,
  revistas: mockRevistas,
  produtos: mockProdutos,
  pedidos: mockPedidos,
  fluxo,
  proximosPassos: [
    "Ligar autenticacao e permissao para separar gerente e vendedora de verdade.",
    "Transformar o preview da vendedora em area logada com filtros do proprio cadastro.",
    "Adicionar exportacao do fechamento mensal para conferencia e arquivo.",
    "Preparar automacoes para leitura de pedidos e avisos pelo WhatsApp.",
  ],
  whatsappDestino: "5511999999999",
  supabaseReady: false,
};
